### PR TITLE
switching to devo mac pool

### PR DESCRIPTION
**Pull request by jftheroux-devolutions**

### CODE REVIEW

**Comment by pdugre** [comment]
Build is broken though, missing msbuild

**Comment by MathieuMorrissette** [comment]
I will add msbuild to the PATH env variable

**Comment by MathieuMorrissette** [comment]
I'm unable to setup xamarin-android correctly. Putting this on hold until I have more time to investigate.

**Comment by pdugre** [comment]
Will be done in  the future :rocket:

**Pull request closed without merging**
